app = "casino-green"
primary_region = "gig"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_NAME = "GREEN"
  APP_ENV = "production"
  LOG_CHANNEL = "stack"

[deploy]
  release_command = "php /app/core/artisan migrate --force"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 20
    soft_limit = 17
    
  [[services.ports]]
    handlers = ["http"]
    port = 80
    
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
